test:main.cpp	
	g++  ./main.cpp -I../Common  -L../Lib64 -I/mnt/hgfs/SVN/Depend/protobuf/X86_6/include  -L/mnt/hgfs/SVN/Depend/protobuf/X86_6/lib -lcommonproto -lprotobuf  -o test
	
	
clean:
	rm test