// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlarmType.proto

#ifndef PROTOBUF_AlarmType_2eproto__INCLUDED
#define PROTOBUF_AlarmType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace arges {
namespace file {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_AlarmType_2eproto();
void protobuf_AssignDesc_AlarmType_2eproto();
void protobuf_ShutdownFile_AlarmType_2eproto();


enum ALARM_TYPE {
  ALARM_FOR_GET_CAPTURE = 897
};
bool ALARM_TYPE_IsValid(int value);
const ALARM_TYPE ALARM_TYPE_MIN = ALARM_FOR_GET_CAPTURE;
const ALARM_TYPE ALARM_TYPE_MAX = ALARM_FOR_GET_CAPTURE;
const int ALARM_TYPE_ARRAYSIZE = ALARM_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* ALARM_TYPE_descriptor();
inline const ::std::string& ALARM_TYPE_Name(ALARM_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    ALARM_TYPE_descriptor(), value);
}
inline bool ALARM_TYPE_Parse(
    const ::std::string& name, ALARM_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ALARM_TYPE>(
    ALARM_TYPE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace file
}  // namespace arges
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::com::arges::file::proto::ALARM_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::arges::file::proto::ALARM_TYPE>() {
  return ::com::arges::file::proto::ALARM_TYPE_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AlarmType_2eproto__INCLUDED
