// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeviceStatusEventReportBean.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "DeviceStatusEventReportBean.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace arges {
namespace file {
namespace proto {

namespace {

const ::google::protobuf::Descriptor* DeviceStatusEventReport_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DeviceStatusEventReport_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_DeviceStatusEventReportBean_2eproto() {
  protobuf_AddDesc_DeviceStatusEventReportBean_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "DeviceStatusEventReportBean.proto");
  GOOGLE_CHECK(file != NULL);
  DeviceStatusEventReport_descriptor_ = file->message_type(0);
  static const int DeviceStatusEventReport_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceStatusEventReport, deviceid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceStatusEventReport, channel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceStatusEventReport, statustype_),
  };
  DeviceStatusEventReport_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DeviceStatusEventReport_descriptor_,
      DeviceStatusEventReport::default_instance_,
      DeviceStatusEventReport_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceStatusEventReport, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeviceStatusEventReport, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DeviceStatusEventReport));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_DeviceStatusEventReportBean_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DeviceStatusEventReport_descriptor_, &DeviceStatusEventReport::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_DeviceStatusEventReportBean_2eproto() {
  delete DeviceStatusEventReport::default_instance_;
  delete DeviceStatusEventReport_reflection_;
  delete DeviceStatusEventReport::_default_deviceid_;
}

void protobuf_AddDesc_DeviceStatusEventReportBean_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!DeviceStatusEventReportBean.proto\022\024com"
    ".arges.file.proto\"a\n\027DeviceStatusEventRe"
    "port\022\031\n\010deviceid\030\001 \001(\t:\007default\022\023\n\007chann"
    "el\030\002 \001(\005:\002-1\022\026\n\nstatustype\030\005 \001(\005:\002-1", 156);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DeviceStatusEventReportBean.proto", &protobuf_RegisterTypes);
  DeviceStatusEventReport::_default_deviceid_ =
      new ::std::string("default", 7);
  DeviceStatusEventReport::default_instance_ = new DeviceStatusEventReport();
  DeviceStatusEventReport::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_DeviceStatusEventReportBean_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_DeviceStatusEventReportBean_2eproto {
  StaticDescriptorInitializer_DeviceStatusEventReportBean_2eproto() {
    protobuf_AddDesc_DeviceStatusEventReportBean_2eproto();
  }
} static_descriptor_initializer_DeviceStatusEventReportBean_2eproto_;

// ===================================================================

::std::string* DeviceStatusEventReport::_default_deviceid_ = NULL;
#ifndef _MSC_VER
const int DeviceStatusEventReport::kDeviceidFieldNumber;
const int DeviceStatusEventReport::kChannelFieldNumber;
const int DeviceStatusEventReport::kStatustypeFieldNumber;
#endif  // !_MSC_VER

DeviceStatusEventReport::DeviceStatusEventReport()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.arges.file.proto.DeviceStatusEventReport)
}

void DeviceStatusEventReport::InitAsDefaultInstance() {
}

DeviceStatusEventReport::DeviceStatusEventReport(const DeviceStatusEventReport& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:com.arges.file.proto.DeviceStatusEventReport)
}

void DeviceStatusEventReport::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  deviceid_ = const_cast< ::std::string*>(_default_deviceid_);
  channel_ = -1;
  statustype_ = -1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DeviceStatusEventReport::~DeviceStatusEventReport() {
  // @@protoc_insertion_point(destructor:com.arges.file.proto.DeviceStatusEventReport)
  SharedDtor();
}

void DeviceStatusEventReport::SharedDtor() {
  if (deviceid_ != _default_deviceid_) {
    delete deviceid_;
  }
  if (this != default_instance_) {
  }
}

void DeviceStatusEventReport::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DeviceStatusEventReport::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DeviceStatusEventReport_descriptor_;
}

const DeviceStatusEventReport& DeviceStatusEventReport::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_DeviceStatusEventReportBean_2eproto();
  return *default_instance_;
}

DeviceStatusEventReport* DeviceStatusEventReport::default_instance_ = NULL;

DeviceStatusEventReport* DeviceStatusEventReport::New() const {
  return new DeviceStatusEventReport;
}

void DeviceStatusEventReport::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_deviceid()) {
      if (deviceid_ != _default_deviceid_) {
        deviceid_->assign(*_default_deviceid_);
      }
    }
    channel_ = -1;
    statustype_ = -1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DeviceStatusEventReport::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.arges.file.proto.DeviceStatusEventReport)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string deviceid = 1 [default = "default"];
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deviceid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->deviceid().data(), this->deviceid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "deviceid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_channel;
        break;
      }

      // optional int32 channel = 2 [default = -1];
      case 2: {
        if (tag == 16) {
         parse_channel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channel_)));
          set_has_channel();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_statustype;
        break;
      }

      // optional int32 statustype = 5 [default = -1];
      case 5: {
        if (tag == 40) {
         parse_statustype:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &statustype_)));
          set_has_statustype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.arges.file.proto.DeviceStatusEventReport)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.arges.file.proto.DeviceStatusEventReport)
  return false;
#undef DO_
}

void DeviceStatusEventReport::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.arges.file.proto.DeviceStatusEventReport)
  // optional string deviceid = 1 [default = "default"];
  if (has_deviceid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->deviceid().data(), this->deviceid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "deviceid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->deviceid(), output);
  }

  // optional int32 channel = 2 [default = -1];
  if (has_channel()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->channel(), output);
  }

  // optional int32 statustype = 5 [default = -1];
  if (has_statustype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->statustype(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:com.arges.file.proto.DeviceStatusEventReport)
}

::google::protobuf::uint8* DeviceStatusEventReport::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.arges.file.proto.DeviceStatusEventReport)
  // optional string deviceid = 1 [default = "default"];
  if (has_deviceid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->deviceid().data(), this->deviceid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "deviceid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->deviceid(), target);
  }

  // optional int32 channel = 2 [default = -1];
  if (has_channel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->channel(), target);
  }

  // optional int32 statustype = 5 [default = -1];
  if (has_statustype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->statustype(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.arges.file.proto.DeviceStatusEventReport)
  return target;
}

int DeviceStatusEventReport::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string deviceid = 1 [default = "default"];
    if (has_deviceid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->deviceid());
    }

    // optional int32 channel = 2 [default = -1];
    if (has_channel()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->channel());
    }

    // optional int32 statustype = 5 [default = -1];
    if (has_statustype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->statustype());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DeviceStatusEventReport::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DeviceStatusEventReport* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DeviceStatusEventReport*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DeviceStatusEventReport::MergeFrom(const DeviceStatusEventReport& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_deviceid()) {
      set_deviceid(from.deviceid());
    }
    if (from.has_channel()) {
      set_channel(from.channel());
    }
    if (from.has_statustype()) {
      set_statustype(from.statustype());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DeviceStatusEventReport::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeviceStatusEventReport::CopyFrom(const DeviceStatusEventReport& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeviceStatusEventReport::IsInitialized() const {

  return true;
}

void DeviceStatusEventReport::Swap(DeviceStatusEventReport* other) {
  if (other != this) {
    std::swap(deviceid_, other->deviceid_);
    std::swap(channel_, other->channel_);
    std::swap(statustype_, other->statustype_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DeviceStatusEventReport::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DeviceStatusEventReport_descriptor_;
  metadata.reflection = DeviceStatusEventReport_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace file
}  // namespace arges
}  // namespace com

// @@protoc_insertion_point(global_scope)
