// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WristBandMacListBean.proto

#ifndef PROTOBUF_WristBandMacListBean_2eproto__INCLUDED
#define PROTOBUF_WristBandMacListBean_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace arges {
namespace file {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_WristBandMacListBean_2eproto();
void protobuf_AssignDesc_WristBandMacListBean_2eproto();
void protobuf_ShutdownFile_WristBandMacListBean_2eproto();

class WristBandMacAddressList;

// ===================================================================

class WristBandMacAddressList : public ::google::protobuf::Message {
 public:
  WristBandMacAddressList();
  virtual ~WristBandMacAddressList();

  WristBandMacAddressList(const WristBandMacAddressList& from);

  inline WristBandMacAddressList& operator=(const WristBandMacAddressList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WristBandMacAddressList& default_instance();

  void Swap(WristBandMacAddressList* other);

  // implements Message ----------------------------------------------

  WristBandMacAddressList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const WristBandMacAddressList& from);
  void MergeFrom(const WristBandMacAddressList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string wristBandMacAddress = 1;
  inline int wristbandmacaddress_size() const;
  inline void clear_wristbandmacaddress();
  static const int kWristBandMacAddressFieldNumber = 1;
  inline const ::std::string& wristbandmacaddress(int index) const;
  inline ::std::string* mutable_wristbandmacaddress(int index);
  inline void set_wristbandmacaddress(int index, const ::std::string& value);
  inline void set_wristbandmacaddress(int index, const char* value);
  inline void set_wristbandmacaddress(int index, const char* value, size_t size);
  inline ::std::string* add_wristbandmacaddress();
  inline void add_wristbandmacaddress(const ::std::string& value);
  inline void add_wristbandmacaddress(const char* value);
  inline void add_wristbandmacaddress(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& wristbandmacaddress() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_wristbandmacaddress();

  // @@protoc_insertion_point(class_scope:com.arges.file.proto.WristBandMacAddressList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> wristbandmacaddress_;
  friend void  protobuf_AddDesc_WristBandMacListBean_2eproto();
  friend void protobuf_AssignDesc_WristBandMacListBean_2eproto();
  friend void protobuf_ShutdownFile_WristBandMacListBean_2eproto();

  void InitAsDefaultInstance();
  static WristBandMacAddressList* default_instance_;
};
// ===================================================================


// ===================================================================

// WristBandMacAddressList

// repeated string wristBandMacAddress = 1;
inline int WristBandMacAddressList::wristbandmacaddress_size() const {
  return wristbandmacaddress_.size();
}
inline void WristBandMacAddressList::clear_wristbandmacaddress() {
  wristbandmacaddress_.Clear();
}
inline const ::std::string& WristBandMacAddressList::wristbandmacaddress(int index) const {
  // @@protoc_insertion_point(field_get:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
  return wristbandmacaddress_.Get(index);
}
inline ::std::string* WristBandMacAddressList::mutable_wristbandmacaddress(int index) {
  // @@protoc_insertion_point(field_mutable:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
  return wristbandmacaddress_.Mutable(index);
}
inline void WristBandMacAddressList::set_wristbandmacaddress(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
  wristbandmacaddress_.Mutable(index)->assign(value);
}
inline void WristBandMacAddressList::set_wristbandmacaddress(int index, const char* value) {
  wristbandmacaddress_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
}
inline void WristBandMacAddressList::set_wristbandmacaddress(int index, const char* value, size_t size) {
  wristbandmacaddress_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
}
inline ::std::string* WristBandMacAddressList::add_wristbandmacaddress() {
  return wristbandmacaddress_.Add();
}
inline void WristBandMacAddressList::add_wristbandmacaddress(const ::std::string& value) {
  wristbandmacaddress_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
}
inline void WristBandMacAddressList::add_wristbandmacaddress(const char* value) {
  wristbandmacaddress_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
}
inline void WristBandMacAddressList::add_wristbandmacaddress(const char* value, size_t size) {
  wristbandmacaddress_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
WristBandMacAddressList::wristbandmacaddress() const {
  // @@protoc_insertion_point(field_list:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
  return wristbandmacaddress_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
WristBandMacAddressList::mutable_wristbandmacaddress() {
  // @@protoc_insertion_point(field_mutable_list:com.arges.file.proto.WristBandMacAddressList.wristBandMacAddress)
  return &wristbandmacaddress_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace file
}  // namespace arges
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_WristBandMacListBean_2eproto__INCLUDED
