// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestVoteRpcBean.proto

#ifndef PROTOBUF_RequestVoteRpcBean_2eproto__INCLUDED
#define PROTOBUF_RequestVoteRpcBean_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace arges {
namespace file {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RequestVoteRpcBean_2eproto();
void protobuf_AssignDesc_RequestVoteRpcBean_2eproto();
void protobuf_ShutdownFile_RequestVoteRpcBean_2eproto();

class RequestVoteRpc;

// ===================================================================

class RequestVoteRpc : public ::google::protobuf::Message {
 public:
  RequestVoteRpc();
  virtual ~RequestVoteRpc();

  RequestVoteRpc(const RequestVoteRpc& from);

  inline RequestVoteRpc& operator=(const RequestVoteRpc& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestVoteRpc& default_instance();

  void Swap(RequestVoteRpc* other);

  // implements Message ----------------------------------------------

  RequestVoteRpc* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestVoteRpc& from);
  void MergeFrom(const RequestVoteRpc& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string term = 1 [default = ""];
  inline bool has_term() const;
  inline void clear_term();
  static const int kTermFieldNumber = 1;
  inline const ::std::string& term() const;
  inline void set_term(const ::std::string& value);
  inline void set_term(const char* value);
  inline void set_term(const char* value, size_t size);
  inline ::std::string* mutable_term();
  inline ::std::string* release_term();
  inline void set_allocated_term(::std::string* term);

  // optional string srcIdentifier = 2 [default = ""];
  inline bool has_srcidentifier() const;
  inline void clear_srcidentifier();
  static const int kSrcIdentifierFieldNumber = 2;
  inline const ::std::string& srcidentifier() const;
  inline void set_srcidentifier(const ::std::string& value);
  inline void set_srcidentifier(const char* value);
  inline void set_srcidentifier(const char* value, size_t size);
  inline ::std::string* mutable_srcidentifier();
  inline ::std::string* release_srcidentifier();
  inline void set_allocated_srcidentifier(::std::string* srcidentifier);

  // @@protoc_insertion_point(class_scope:com.arges.file.proto.RequestVoteRpc)
 private:
  inline void set_has_term();
  inline void clear_has_term();
  inline void set_has_srcidentifier();
  inline void clear_has_srcidentifier();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* term_;
  ::std::string* srcidentifier_;
  friend void  protobuf_AddDesc_RequestVoteRpcBean_2eproto();
  friend void protobuf_AssignDesc_RequestVoteRpcBean_2eproto();
  friend void protobuf_ShutdownFile_RequestVoteRpcBean_2eproto();

  void InitAsDefaultInstance();
  static RequestVoteRpc* default_instance_;
};
// ===================================================================


// ===================================================================

// RequestVoteRpc

// optional string term = 1 [default = ""];
inline bool RequestVoteRpc::has_term() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestVoteRpc::set_has_term() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestVoteRpc::clear_has_term() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestVoteRpc::clear_term() {
  if (term_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    term_->clear();
  }
  clear_has_term();
}
inline const ::std::string& RequestVoteRpc::term() const {
  // @@protoc_insertion_point(field_get:com.arges.file.proto.RequestVoteRpc.term)
  return *term_;
}
inline void RequestVoteRpc::set_term(const ::std::string& value) {
  set_has_term();
  if (term_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    term_ = new ::std::string;
  }
  term_->assign(value);
  // @@protoc_insertion_point(field_set:com.arges.file.proto.RequestVoteRpc.term)
}
inline void RequestVoteRpc::set_term(const char* value) {
  set_has_term();
  if (term_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    term_ = new ::std::string;
  }
  term_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.arges.file.proto.RequestVoteRpc.term)
}
inline void RequestVoteRpc::set_term(const char* value, size_t size) {
  set_has_term();
  if (term_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    term_ = new ::std::string;
  }
  term_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.arges.file.proto.RequestVoteRpc.term)
}
inline ::std::string* RequestVoteRpc::mutable_term() {
  set_has_term();
  if (term_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    term_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.arges.file.proto.RequestVoteRpc.term)
  return term_;
}
inline ::std::string* RequestVoteRpc::release_term() {
  clear_has_term();
  if (term_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = term_;
    term_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RequestVoteRpc::set_allocated_term(::std::string* term) {
  if (term_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete term_;
  }
  if (term) {
    set_has_term();
    term_ = term;
  } else {
    clear_has_term();
    term_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.arges.file.proto.RequestVoteRpc.term)
}

// optional string srcIdentifier = 2 [default = ""];
inline bool RequestVoteRpc::has_srcidentifier() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestVoteRpc::set_has_srcidentifier() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestVoteRpc::clear_has_srcidentifier() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestVoteRpc::clear_srcidentifier() {
  if (srcidentifier_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    srcidentifier_->clear();
  }
  clear_has_srcidentifier();
}
inline const ::std::string& RequestVoteRpc::srcidentifier() const {
  // @@protoc_insertion_point(field_get:com.arges.file.proto.RequestVoteRpc.srcIdentifier)
  return *srcidentifier_;
}
inline void RequestVoteRpc::set_srcidentifier(const ::std::string& value) {
  set_has_srcidentifier();
  if (srcidentifier_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    srcidentifier_ = new ::std::string;
  }
  srcidentifier_->assign(value);
  // @@protoc_insertion_point(field_set:com.arges.file.proto.RequestVoteRpc.srcIdentifier)
}
inline void RequestVoteRpc::set_srcidentifier(const char* value) {
  set_has_srcidentifier();
  if (srcidentifier_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    srcidentifier_ = new ::std::string;
  }
  srcidentifier_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.arges.file.proto.RequestVoteRpc.srcIdentifier)
}
inline void RequestVoteRpc::set_srcidentifier(const char* value, size_t size) {
  set_has_srcidentifier();
  if (srcidentifier_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    srcidentifier_ = new ::std::string;
  }
  srcidentifier_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.arges.file.proto.RequestVoteRpc.srcIdentifier)
}
inline ::std::string* RequestVoteRpc::mutable_srcidentifier() {
  set_has_srcidentifier();
  if (srcidentifier_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    srcidentifier_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.arges.file.proto.RequestVoteRpc.srcIdentifier)
  return srcidentifier_;
}
inline ::std::string* RequestVoteRpc::release_srcidentifier() {
  clear_has_srcidentifier();
  if (srcidentifier_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = srcidentifier_;
    srcidentifier_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RequestVoteRpc::set_allocated_srcidentifier(::std::string* srcidentifier) {
  if (srcidentifier_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete srcidentifier_;
  }
  if (srcidentifier) {
    set_has_srcidentifier();
    srcidentifier_ = srcidentifier;
  } else {
    clear_has_srcidentifier();
    srcidentifier_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.arges.file.proto.RequestVoteRpc.srcIdentifier)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace file
}  // namespace arges
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RequestVoteRpcBean_2eproto__INCLUDED
